minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true

allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
  unrs-resolver: true
trustPolicyIgnoreAfter: 10080
trustPolicyExclude:
  - eslint-import-resolver-typescript@3.10.1
  - '@effect/platform-node-shared@4.0.0-beta.70'
  - effect@4.0.0-beta.70
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.13'
  - '@better-auth/drizzle-adapter@1.6.13'
  - '@better-auth/kysely-adapter@1.6.13'
  - '@better-auth/memory-adapter@1.6.13'
  - '@better-auth/mongo-adapter@1.6.13'
  - '@better-auth/passkey@1.6.13'
  - '@better-auth/prisma-adapter@1.6.13'
  - '@better-auth/telemetry@1.6.13'
  - '@better-auth/utils@0.4.1'
  - better-auth@1.6.13
  - '@oxc-resolver/binding-android-arm-eabi@11.20.0'
  - '@oxc-resolver/binding-android-arm64@11.20.0'
  - '@oxc-resolver/binding-darwin-arm64@11.20.0'
  - '@oxc-resolver/binding-darwin-x64@11.20.0'
  - '@oxc-resolver/binding-freebsd-x64@11.20.0'
  - '@oxc-resolver/binding-linux-arm-gnueabihf@11.20.0'
  - '@oxc-resolver/binding-linux-arm-musleabihf@11.20.0'
  - '@oxc-resolver/binding-linux-arm64-gnu@11.20.0'
  - '@oxc-resolver/binding-linux-arm64-musl@11.20.0'
  - '@oxc-resolver/binding-linux-ppc64-gnu@11.20.0'
  - '@oxc-resolver/binding-linux-riscv64-gnu@11.20.0'
  - '@oxc-resolver/binding-linux-riscv64-musl@11.20.0'
  - '@oxc-resolver/binding-linux-s390x-gnu@11.20.0'
  - '@oxc-resolver/binding-linux-x64-gnu@11.20.0'
  - '@oxc-resolver/binding-linux-x64-musl@11.20.0'
  - '@oxc-resolver/binding-openharmony-arm64@11.20.0'
  - '@oxc-resolver/binding-wasm32-wasi@11.20.0'
  - '@oxc-resolver/binding-win32-arm64-msvc@11.20.0'
  - '@oxc-resolver/binding-win32-x64-msvc@11.20.0'
  - '@simplewebauthn/server@13.3.1'
  - brace-expansion@1.1.15
  - js-yaml@4.2.0
  - lru-cache@11.5.1
  - lucide-react@1.17.0
  - oxc-resolver@11.20.0
  - which-typed-array@1.1.21
  - oxlint-plugin-react-doctor@0.2.14
  - react-doctor@0.2.14
  - react-email@6.5.0
storeDir: ./.pnpm-store/v11
