-- Supabase Storage setup for Quiniela
-- Buckets:
--   - avatars           (public read; signed uploads generated server-side)
--   - tournament-assets (public read; signed uploads generated server-side)

insert into storage.buckets (id, name, public)
values
  ('avatars', 'avatars', true),
  ('tournament-assets', 'tournament-assets', true)
on conflict (id) do update
set public = excluded.public;

drop policy if exists "storage_objects_select_public_assets" on storage.objects;
drop policy if exists "storage_objects_insert_own_avatar" on storage.objects;
drop policy if exists "storage_objects_update_own_avatar" on storage.objects;
drop policy if exists "storage_objects_delete_own_avatar" on storage.objects;

-- Optional hardening: authenticated users may view metadata for these buckets.
create policy "storage_objects_select_public_assets"
on storage.objects
for select
to authenticated
using (bucket_id in ('avatars', 'tournament-assets'));

-- Users can manage only their own avatar object path.
create policy "storage_objects_insert_own_avatar"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = 'users'
  and (storage.foldername(name))[2] = (select auth.uid()::text)
);

create policy "storage_objects_update_own_avatar"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = 'users'
  and (storage.foldername(name))[2] = (select auth.uid()::text)
)
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = 'users'
  and (storage.foldername(name))[2] = (select auth.uid()::text)
);

create policy "storage_objects_delete_own_avatar"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = 'users'
  and (storage.foldername(name))[2] = (select auth.uid()::text)
);

-- Tournament logos are uploaded through signed URLs generated by the server for OWNERs.
-- Keep direct client-side writes closed by default. If later you want DB-enforced writes,
-- add an insert/update/delete policy tied to your membership model.
